### ISSUE TITLE
[suggestion] Add support for gamepads/controllers

### ISSUE THREAD

**Issue by TheKevinGDX** [HecticKiwi/Web-Osu-Mania#12]
It would be great to have gamepad support, as my phone's touchscreen often fails. That's why I always carry a gamepad with me to play games when I'm out and about.

While osu!Lazer works perfectly with a gamepad, the performance isn't the best on low-end devices 🙁

**Comment by HecticKiwi** [comment]
Since the site already supports keyboard, would it work to use an app that maps your gamepad to keyboard presses? If not I'll look into this, but no promises when as 1. this seems to be a very rare use case and 2. coursework is ramping up 😞

**Comment by HecticKiwi** [comment]
I just added a crude implementation, it supports gamepad buttons but not joystick inputs 🙃

If you need more just reopen this issue
