### ISSUE TITLE
let up put our own skins

### ISSUE THREAD

**Issue by sunroll1** [HecticKiwi/Web-Osu-Mania#13]
let us put our own mania/all mode skins in or ones that we downloaded I think it would be cool

**Comment by HecticKiwi** [comment]
Sorry I think it'd be cool too, but there's too much to figure out in osu skins:

- How the skin.ini settings work
- @2x images
- Animated skin elements
- Different skin version numbers
- Scaling at different screen sizes

This why the site uses skin elements drawn from scratch, it's much easier to code that way.

**Comment by SoxRegretsLife** [comment]
@HecticKiwi can you make advanced skin customization better so that you can customize the colour of hold notes

**Comment by HecticKiwi** [comment]
Do you mean the heads of hold notes?

**Comment by HecticKiwi** [comment]
I've created an issue to track its progress👍
