### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by sheepyboiyt** [HecticKiwi/Web-Osu-Mania#14]
will a leader board exist. and here is a issue or i think. i only know this happens for one but everything is wrong with a beat map. like when im in it the whole name changes the song changes and the even the background. One more thing 1/100 chance u add this. Adding custom beatmaps from this website its self. LOL thats all :)

**Comment by HecticKiwi** [comment]
- Not planning on adding leaderboards at the moment, but that may change in the future
- Which beatmap are you referring to?
- Sorry, but this site uses beatmaps from the official osu, which means there's no way of uploading custom beatmaps (unless you mean playing a .osz file) ;)
