### ISSUE TITLE
Mobile touch

### ISSUE THREAD

**Issue by MalekAlshaer** [HecticKiwi/Web-Osu-Mania#17]
When holding 3 or 4 fingers at once they bars/circles stay in holding position even after releasing the fingers with 1 or 2 fingers doesn't happen only at 3 starts the problem

**Comment by HecticKiwi** [comment]
It seems to work fine for me, I can hold and release 7 fingers correctly on my android phone and tablet. Maybe it's your device, can you try on another one?

**Comment by MalekAlshaer** [comment]
I have tried on my Xiaomi redmi note 11s and my xiaomi pad 6 and both have the same problem

**Comment by HecticKiwi** [comment]
From Googling it looks like an issue with the touch gestures for Xiaomi devices. These threads all seem to have the same solution, so try it out on your web browser app:

https://xdaforums.com/t/is-there-any-way-to-actually-disable-multi-touch-gestures.4635691/
![image](https://github.com/user-attachments/assets/14aea509-acef-47cd-94e2-c0f70329828e)

https://www.reddit.com/r/rhythmgames/comments/188zilf/my_xiaomi_phone_doesnt_detect_morethan2finger/
![image](https://github.com/user-attachments/assets/9a5502f7-43f8-47fb-ba81-12b5753b4245)

https://www.reddit.com/r/PocoPhones/comments/1bfcx94/poco_xiaomi_x6_pro_3_finger_touch_screen_problem/
![image](https://github.com/user-attachments/assets/10f7889b-5248-48dc-9b8a-54f01626bb81)

**Comment by MalekAlshaer** [comment]
oh thanks now it works
