### ISSUE TITLE
Add .osz file support

### ISSUE THREAD

**Issue by ericshu6** [HecticKiwi/Web-Osu-Mania#22]
I am playing on a network where all mirrors are blocked, except [BeatConnect](https://beatconnect.io). Sadly, their API is not public, and I can only download `.osz` files from the website. Because of this, I would like support for uploading our own `.osz` files instead of solely relying on APIs.

**Comment by HecticKiwi** [comment]
Good idea, I'll work on implementing this.

**Comment by HecticKiwi** [comment]
@ericshu6 Just making sure, but you can still access the official osu API, right? It provides the list of beatmaps, hopefully you're still able to see that

I ask because when you upload a `.osz`, I'll need to query that API to get the cover image URL, preview audio URL, and diff star ratings. In theory it's possible to obtain these from the `.osz`, but it's significantly more work (especially the star rating calculation)

**Comment by ericshu6** [comment]
The osu! website is blocked on my network :(

**Comment by HecticKiwi** [comment]
I've just added two new settings, either one should solve your issue:

![image](https://github.com/user-attachments/assets/303dbdf4-5c6f-4e7f-99a0-1d8f8808fd1d)

**Proxy Downloads**: In theory, you should be able to get around the blocks by proxying the download requests through my site's server, which should be unblocked considering you can access my site in the first place. I recommend using this as it should allow you to use the site normally, without having to download maps through BeatConnect yourself.

**Upload Beatmap**: If you still want to use your downloaded files, you can load them as well.

Let me know if these actually work xd

**Comment by ericshu6** [comment]
I just tested this on my home network, and these settings work perfectly. I'm not sure if they will work on a network with filters, but these look great so far!

**Comment by HecticKiwi** [comment]
The next time you're on that network that blocks the mirrors, try these settings again. If you can confirm that this still works I can close this issue (or close it yourself if you're able) 👍

**Comment by ericshu6** [comment]
These settings work perfectly on a filtered network! Thanks for implementing this so fast 😁
