### ISSUE TITLE
problems.

### ISSUE THREAD

**Issue by Ren4Real** [HecticKiwi/Web-Osu-Mania#23]
hey! I tried the game, there are some problems where the song  is uhh... fast forwarded. like- the music. I want to figure out how to fix it! thanks.

**Comment by HecticKiwi** [comment]
The music speed is normal on my end - did you accidentally change the song speed in the mods tab? 1x means normal speed

![image](https://github.com/user-attachments/assets/c5b92c18-67ce-49eb-a459-d2976bbabaa5)
