### ISSUE TITLE
Suggestion: Any Circle skin please

### ISSUE THREAD

**Issue by CIH212** [HecticKiwi/Web-Osu-Mania#3]
Any circle skin.

I know its a skill issue on my part but my accuracy is bad with the bar skin.

**Comment by HecticKiwi** [comment]
Sure thing, working on it right now!
However, no guarantees on when it'll be done as I need to balance this and coursework

**Comment by HecticKiwi** [comment]
Done, didn't take too long after I decided to redo the graphics from scratch. You can find the option under the Display header.

![image](https://github.com/user-attachments/assets/13051afc-7f78-443c-ac90-7c200426a592)

Let me know if I need to adjust anything
